[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ExpectedOldHead,[Parameter(Mandatory=$true)][string]$ExpectedReleaseHead,[Parameter(Mandatory=$true)][string]$ReleaseCandidateRoot,[Parameter(Mandatory=$true)][string]$BackupManifest,[switch]$Execute,[string]$ApprovalPhrase)
$ErrorActionPreference='Stop'; $ExpectedRoot='C:\VAMBAM\Projects\OTG\data_streamlit\opensea_sales'; $ExpectedPort=8502; $ExpectedApp='app_opensea_sales.py'; $ForbiddenPorts=@(8501,8504); $ExpectedMigrations=@('sql/add_site_visit_trader_mode.sql','sql/create_site_product_events.sql','sql/create_user_feedback.sql')
function Assert-Guards { if($ExpectedRoot -ne 'C:\VAMBAM\Projects\OTG\data_streamlit\opensea_sales'){throw 'ROOT_GUARD_FAILED'}; if($ExpectedPort -in $ForbiddenPorts -or $ExpectedApp -eq 'app_gaming_marketplace.py'){throw 'FORBIDDEN_TARGET'}; if($ReleaseCandidateRoot.StartsWith($ExpectedRoot,[StringComparison]::OrdinalIgnoreCase)){throw 'RUNTIME_MUST_BE_OUTSIDE_PRODUCTION'}; if(Test-Path $ReleaseCandidateRoot){$null}; if((git -c "safe.directory=$ExpectedRoot" -C $ExpectedRoot status --porcelain)){throw 'PRODUCTION_WORKTREE_NOT_CLEAN'} }
function Invoke-GuardedAction([scriptblock]$Action,[string]$Name){if(-not $Execute){"PLAN_ONLY=$Name";return};& $Action}
Assert-Guards; if($Execute -and $ApprovalPhrase -ne 'UPDATE_OTG_ANALYTICS_8502'){throw 'APPROVAL_PHRASE_REQUIRED'}
$old=(git -c "safe.directory=$ExpectedRoot" -C $ExpectedRoot rev-parse HEAD); if($old -ne $ExpectedOldHead){throw 'EXPECTED_OLD_HEAD_MISMATCH'}
$main=(git -c "safe.directory=$ExpectedRoot" -C $ExpectedRoot rev-parse origin/main 2>$null); "MODE=$(if($Execute){'EXECUTE'}else{'DRY_RUN'})"; "OLD_HEAD=$old"; "RELEASE_HEAD=$ExpectedReleaseHead"; "MAIN_PROMOTION_REQUIRED=$(if($main -ne $ExpectedReleaseHead){'YES'}else{'NO'})"; "RUNTIME_PLAN=PASS"; "ARTIFACT_REFRESH_PLAN=PASS"; "MIGRATION_PLAN_COUNT=$($ExpectedMigrations.Count)"; "TARGET_PORT=$ExpectedPort"; "FORBIDDEN_TARGET_GUARDS=PASS"
if($Execute -and $main -ne $ExpectedReleaseHead){throw 'MAIN_PROMOTION_REQUIRED'}; if($Execute -and -not(Test-Path $BackupManifest)){throw 'BACKUP_MANIFEST_REQUIRED'}
Invoke-GuardedAction { git -C $ExpectedRoot merge --ff-only $ExpectedReleaseHead } 'DEPLOY_MUTATIONS'; "MUTATION_EXECUTED=$(if($Execute){'YES'}else{'NO'})"
