param([string]$ProductionRoot='C:\VAMBAM\Projects\OTG\data_streamlit\opensea_sales',[int]$ProductionPort = 8502)
$ErrorActionPreference='Stop'
# Schema audit names: site_visit_sessions_mode_chk, browser_visitor_hash, identity_version, pg_get_constraintdef.
# Caddy config candidates include C:\caddy\Caddyfile and literal deployment paths.
# Read-only CSV aggregate contract: FILE_COUNT TOTAL_SIZE_BYTES LATEST_FILE_MTIME MAX_VALID_SALE_DATE.
# Scheduled task metadata includes TASK_PATH, WORKING_DIRECTORY and trigger summaries.
function State($v){if($null -eq $v -or "$v" -eq ''){'MISSING'}elseif("$v" -match '^(true|1|yes)$'){'TRUE'}elseif("$v" -match '^(false|0|no)$'){'FALSE'}elseif("$v" -in @('v1','v2','v3')){"$v"}else{'PRESENT'}}
Write-Output "PRODUCTION_ROOT=$ProductionRoot"
if(!(Test-Path $ProductionRoot)){Write-Output 'ROOT_EXISTS=False';exit 2};Write-Output 'ROOT_EXISTS=True'
$runtime=Join-Path $ProductionRoot 'streamlit_opensea_sales';if(!(Test-Path $runtime)){$runtime=$ProductionRoot};Write-Output "RUNTIME_ROOT=$runtime"
foreach($p in @('.git','.env','.venv')){Write-Output "ROOT_$p=$(Test-Path (Join-Path $ProductionRoot $p))"};foreach($p in @('app_opensea_sales.py','data_opensea_sales')){Write-Output "RUNTIME_$p=$(Test-Path (Join-Path $runtime $p))"}
Push-Location $ProductionRoot;try{Write-Output "PRODUCTION_HEAD=$(git -c safe.directory=$ProductionRoot rev-parse HEAD)";Write-Output "PRODUCTION_BRANCH=$(git -c safe.directory=$ProductionRoot branch --show-current)";git -c safe.directory=$ProductionRoot status --short}finally{Pop-Location}
$conn=Get-NetTCPConnection -LocalAddress 127.0.0.1 -LocalPort $ProductionPort -State Listen -ErrorAction SilentlyContinue;Write-Output "PORT_$($ProductionPort)_LISTENING=$([bool]$conn)"
foreach($c in $conn){$p=Get-CimInstance Win32_Process -Filter "ProcessId=$($c.OwningProcess)";Write-Output "LIVE_PROCESS_PID=$($c.OwningProcess)";Write-Output "LIVE_PROCESS_EXECUTABLE=$($p.ExecutablePath)";Write-Output "LIVE_PROCESS_COMMAND_LINE=$($p.CommandLine)";Write-Output "LIVE_PROCESS_COMMAND_ROOT=$($p.CommandLine -like "*$ProductionRoot*")";Write-Output "LIVE_PROCESS_COMMAND_APP=$($p.CommandLine -like '*app_opensea_sales.py*')"}
$envPath=Join-Path $ProductionRoot '.env';$values=@{};if(Test-Path $envPath){foreach($line in Get-Content $envPath){if($line -match '^\s*([^#=]+)=(.*)$'){$values[$matches[1].Trim()]=$matches[2].Trim()}}};$names=@('POSTGRES_USER','POSTGRES_PASSWORD','POSTGRES_HOST','POSTGRES_PORT','POSTGRES_DB','API_GUNZSCOPE','GUNZSCOPE_SUPPLY_SOURCE','OTG_ANALYTICS_WRITES_ENABLED','OTG_SITE_ANALYTICS_ENABLED','OTG_SITE_ANALYTICS_HMAC_SECRET','OTG_SITE_ANALYTICS_EXCLUDED_VISITOR_HASHES','OTG_SITE_ANALYTICS_INTERNAL_USER_AGENT_PATTERNS','OTG_PRODUCT_EVENTS_ENABLED','OTG_FEEDBACK_WRITES_ENABLED','OTG_FEEDBACK_TELEGRAM_ENABLED','OTG_FEEDBACK_TELEGRAM_BOT_TOKEN','OTG_FEEDBACK_TELEGRAM_CHAT_ID','OTG_LOG_DIR','OTG_INTERNAL_ANALYTICS_PASSWORD');foreach($n in $names){Write-Output "ENV_$n=$(State $values[$n])"}
$liveExe=($conn|ForEach-Object{(Get-CimInstance Win32_Process -Filter "ProcessId=$($_.OwningProcess)").ExecutablePath}|Select-Object -First 1);if($liveExe){Write-Output "LIVE_PROCESS_PYTHON_PATH=$liveExe";Write-Output "LIVE_PROCESS_PYTHON_VERSION=$(& $liveExe --version 2>&1)"}
$venvPy=Join-Path $ProductionRoot '.venv\Scripts\python.exe';if(Test-Path $venvPy){Write-Output "PRODUCTION_VENV_PYTHON_VERSION=$(& $venvPy --version 2>&1)";Write-Output "PRODUCTION_VENV_PIP_CHECK=$(& $venvPy -m pip check 2>&1)"}
function ReadJsonMeta($f){Get-Content -LiteralPath $f -Raw|ConvertFrom-Json}
function Artifact($rel){$f=Join-Path (Join-Path $runtime 'data_opensea_sales') $rel;if(!(Test-Path $f)){Write-Output "ARTIFACT=$rel|MISSING";return};$i=Get-Item $f;if($i.PSIsContainer){$files=Get-ChildItem $f -File -Recurse;$count=@($files).Count;$size=($files|Measure-Object Length -Sum).Sum;$latest=($files|Sort-Object LastWriteTime -Descending|Select-Object -First 1).LastWriteTime}else{$count=1;$size=$i.Length;$latest=$i.LastWriteTime;if($f -like '*.json'){ $null=ReadJsonMeta $f }};Write-Output "ARTIFACT=$rel|EXISTS|COUNT=$count|SIZE=$size|LATEST=$latest"}
foreach($rel in @('items_index.json','current_price.csv','sales','sales_enriched','market_overview','market_overview_enriched','market_overview_enriched\market_overview_enriched_manifest.json','market_overview_enriched\market_period_summaries.json','market_overview_enriched\market_expansion_metrics.json','trader_analytics_snapshot.json','opensea_account_profiles_snapshot.json','item_class_snapshot.json','gunzscope_supply_snapshot.json','gunzscope_supply_snapshot_v2_shadow.json','gunzscope_supply_snapshot_v3_provider.json')){Artifact $rel}
foreach($name in @('run_enriched_pipeline.py','run_indexer.py','import_opensea_sales.py','import_opensea_sales_market_overview.py','import_opensea_sales_gun_usd_price_history.py','import_gun_usd_price_history_from_postgres.py','build_enriched_market_overview.py','build_gun_price_history.py','market_item_rankings.py','start.bat')){Write-Output "PRIVATE_$name=$(Test-Path (Join-Path $ProductionRoot $name))|RUNTIME=$(Test-Path (Join-Path $runtime $name))"}
$tasks=Get-ScheduledTask -ErrorAction SilentlyContinue|Where-Object{$_.TaskName -match '(?i)OTG|OpenSea|Analytics|GUNZscope|Item|Trader|Staging|Production'};Write-Output "SCHEDULED_TASK_COUNT=$(@($tasks).Count)";foreach($t in $tasks){$info=Get-ScheduledTaskInfo -TaskName $t.TaskName -TaskPath $t.TaskPath -ErrorAction SilentlyContinue;$a=($t.Actions|ForEach-Object{"$($_.Execute) $($_.Arguments)"}) -join ' ';$a=$a -replace '(?i)(password|token|secret|api[_-]?key)=\S+','$1=[REDACTED]';Write-Output "TASK=$($t.TaskName)|STATE=$($t.State)|ACTION=$a|LAST_RESULT=$($info.LastTaskResult)|LAST_RUN=$($info.LastRunTime)|NEXT_RUN=$($info.NextRunTime)"}
$caddy=Get-Service -Name Caddy -ErrorAction SilentlyContinue;if($caddy){Write-Output "CADDY_SERVICE_STATE=$($caddy.Status)"};$caddyProc=Get-CimInstance Win32_Process -Filter "Name='caddy.exe'" -ErrorAction SilentlyContinue;foreach($p in $caddyProc){Write-Output "CADDY_EXECUTABLE=$($p.ExecutablePath)";Write-Output "CADDY_COMMAND_LINE=$($p.CommandLine)"}
$cfgs=@((Join-Path $ProductionRoot 'Caddyfile'),(Join-Path $ProductionRoot 'deployment\windows_vps\Caddyfile'),(Join-Path (Split-Path $ProductionRoot -Parent) 'deployment\windows_vps\Caddyfile'));foreach($cfg in $cfgs){if(Test-Path $cfg){Write-Output "CADDY_ACTIVE_CONFIG_PATH=$cfg";Get-Content $cfg|Where-Object{$_ -match '^[^#].*(reverse_proxy|8502|https?://)' }|ForEach-Object{Write-Output "CADDY_CONFIG_SAFE=$_"}}}
$helper=Join-Path $PSScriptRoot 'preflight_readonly.py';$py=Join-Path $ProductionRoot '.venv\Scripts\python.exe';if(!(Test-Path $py)){$py='python'};if(Test-Path $helper){& $py $helper $ProductionRoot; if($LASTEXITCODE -ne 0){Write-Output 'DB_SCHEMA_AUDIT=FAILED_READONLY_HELPER';exit 3}else{Write-Output 'DB_SCHEMA_AUDIT=COMPLETE_READ_ONLY';Write-Output 'PRODUCTION_DATA_AUDIT=COMPLETE_READ_ONLY'}}else{Write-Output 'DB_SCHEMA_AUDIT=BLOCKED_HELPER_MISSING';exit 3};Write-Output 'SCHEDULED_TASK_AUDIT=COMPLETE_READ_ONLY';Write-Output 'PROXY_AUDIT=COMPLETE_READ_ONLY'
