Set-StrictMode -Version Latest

# Side-effect-free shared safety module.  Public scripts build a context and
# call the same Invoke-*Core function regardless of execution mode.
$script:ExpectedRoot = 'C:\VAMBAM\Projects\OTG\data_streamlit\opensea_sales'
$script:ExpectedApp = Join-Path $script:ExpectedRoot 'streamlit_opensea_sales\app_opensea_sales.py'
$script:ExpectedPort = 8502
$script:ExpectedRuntimeRoot = 'C:\VAMBAM\Projects\OTG\runtime\opensea_sales'
$script:SimulationPrefix = 'C:\VAMBAM\Projects\OTG\DEV\production_tooling_sandbox_109'
$script:ForbiddenPorts = @(8501,8504)
$script:ForbiddenApp = 'app_gaming_marketplace.py'
$script:ManagedTasks = @('OTG_Derived_Data_Refresh_Production','OTG_Metadata_Refresh_Production')
$script:AllowedMigrations = @('sql/add_site_visit_trader_mode.sql','sql/create_site_product_events.sql','sql/create_user_feedback.sql')

function Write-KV([string]$Name,[object]$Value) { Write-Output ($Name+'='+[string]$Value) }
function Get-Sha256([string]$Path) { return (Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash.ToLowerInvariant() }
function Write-AtomicText([string]$Path,[string]$Text) {
    $parent=Split-Path -Parent $Path
    if(-not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null}
    $tmp=$Path+'.tmp.'+[guid]::NewGuid().ToString('N')
    [IO.File]::WriteAllText($tmp,$Text,(New-Object Text.UTF8Encoding($false)))
    Move-Item -LiteralPath $tmp -Destination $Path -Force
}
function Write-AtomicJson([string]$Path,[object]$Value) { Write-AtomicText $Path ($Value|ConvertTo-Json -Depth 40) }

function Assert-ProductionTarget {
    param([string]$Root=$script:ExpectedRoot,[int]$Port=$script:ExpectedPort,[string]$App=$script:ExpectedApp)
    if($Root -ne $script:ExpectedRoot -or $Port -ne $script:ExpectedPort -or $App -ne $script:ExpectedApp){throw 'PRODUCTION_TARGET_GUARD_FAILED'}
    if($Port -in $script:ForbiddenPorts -or $App -match [regex]::Escape($script:ForbiddenApp)){throw 'FORBIDDEN_TARGET_GUARD_FAILED'}
    return $true
}
function Assert-SimulationTarget {
    param([string]$Root,[int]$Port,[string]$App)
    $full=[IO.Path]::GetFullPath($Root);$prefix=([IO.Path]::GetFullPath($script:SimulationPrefix)).TrimEnd('\')+'\'
    if($full -ne $prefix.TrimEnd('\') -and -not $full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw 'SIMULATION_CONTEXT_ROOT_GUARD_FAILED'}
    if($full -match '(?i)gaming_marketplace|\\staging(?:\\|$)' -or $full -eq $script:ExpectedRoot){throw 'SIMULATION_CONTEXT_PRODUCTION_PATH_GUARD_FAILED'}
    if($Port -in @($script:ExpectedPort,8501,8504) -or $Port -lt 1024 -or $Port -gt 65535){throw 'SIMULATION_CONTEXT_FORBIDDEN_PORT_GUARD_FAILED'}
    if($App -match '(?i)app_gaming_marketplace|caddy'){throw 'SIMULATION_CONTEXT_APP_GUARD_FAILED'}
    return $true
}
function Assert-Context([object]$Context) {
    if($Context.Mode -eq 'PRODUCTION'){Assert-ProductionTarget $Context.Root $Context.Port $Context.AppPath|Out-Null}
    elseif($Context.Mode -eq 'SIMULATION'){Assert-SimulationTarget $Context.Root $Context.Port $Context.AppPath|Out-Null}
    else{throw 'UNKNOWN_EXECUTION_CONTEXT'}
    if($Context.Port -in $script:ForbiddenPorts -or $Context.AppPath -match [regex]::Escape($script:ForbiddenApp)){throw 'FORBIDDEN_TARGET_GUARD_FAILED'}
}
function Assert-Approval([switch]$Execute,[string]$Actual,[string]$Expected){if($Execute -and $Actual -ne $Expected){throw 'APPROVAL_PHRASE_REQUIRED'}}

function Get-SafeEnv([string]$Path) {
    $out=@{}
    if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){return $out}
    foreach($line in Get-Content -LiteralPath $Path){
        if($line -match '^\s*export\s+'){$line=$line -replace '^\s*export\s+',''}
        if($line -match '^\s*([^#=][^=]*)=(.*)$'){$k=$Matches[1].Trim();$v=$Matches[2].Trim();if(($v.StartsWith('"') -and $v.EndsWith('"')) -or ($v.StartsWith("'") -and $v.EndsWith("'"))){$v=$v.Substring(1,$v.Length-2)};$out[$k]=$v}
    }
    return $out
}
function Get-DatabaseEnvironment([string]$EnvPath,[switch]$Required) {
    $raw=Get-SafeEnv $EnvPath;$map=@{PGHOST='POSTGRES_HOST';PGPORT='POSTGRES_PORT';PGUSER='POSTGRES_USER';PGPASSWORD='POSTGRES_PASSWORD';PGDATABASE='POSTGRES_DB'};$out=@{}
    foreach($k in $map.Keys){$source=$map[$k];if($raw.ContainsKey($source) -and [string]$raw[$source] -ne ''){$out[$k]=[string]$raw[$source]}elseif($Required){throw ('REQUIRED_DB_ENV_MISSING:'+ $source)}};return $out
}
function Get-PostgresTools {
    $out=@{}
    foreach($n in @('pg_dump','pg_restore','psql')){
        $c=Get-Command ($n+'.exe') -ErrorAction SilentlyContinue
        if(-not $c){$c=Get-Command $n -ErrorAction SilentlyContinue}
        if(-not $c){foreach($p in @('C:\Program Files\PostgreSQL\18\bin\'+$n+'.exe','C:\Program Files\PostgreSQL\17\bin\'+$n+'.exe')){if(Test-Path -LiteralPath $p -PathType Leaf){$c=Get-Item $p;break}}}
        if($c){if($c.PSObject.Properties.Name -contains 'Source' -and $c.Source){$out[$n]=$c.Source}else{$out[$n]=$c.FullName}}
    }
    return $out
}
function Get-ToolVersion([string]$Path){if(-not $Path){return ''};try{return ((& $Path '--version' 2>&1)|Select-Object -First 1).ToString().Trim()}catch{return ''}}

function New-ProductionExecutionContext {
    param([hashtable]$Arguments)
    Assert-ProductionTarget|Out-Null
    return [pscustomobject]@{Mode='PRODUCTION';Root=$script:ExpectedRoot;RuntimeRoot=$script:ExpectedRuntimeRoot;AppPath=$script:ExpectedApp;Port=8502;EnvPath=(Join-Path $script:ExpectedRoot '.env');DataRoot=(Join-Path $script:ExpectedRoot 'streamlit_opensea_sales\data_opensea_sales');RepoRoot=$script:ExpectedRoot;ReleaseRoot=$Arguments.ReleaseRoot;ReleasePython=$Arguments.ReleasePython;BackupRoot=$Arguments.BackupRoot;PreparedReleaseManifest=$Arguments.PreparedReleaseManifest;ExpectedOldHead=$Arguments.ExpectedOldHead;ExpectedReleaseHead=$Arguments.ExpectedReleaseHead}
}
function New-SimulationExecutionContext {
    param([hashtable]$Arguments)
    $root=[IO.Path]::GetFullPath($Arguments.SimulationRoot);$app=Join-Path $root 'production\streamlit_opensea_sales\app_opensea_sales.py';Assert-SimulationTarget $root ([int]$Arguments.SimulationPort) $app|Out-Null
    $old='old';$release='release';if($Arguments.ExpectedOldHead){$old=$Arguments.ExpectedOldHead};if($Arguments.ExpectedReleaseHead){$release=$Arguments.ExpectedReleaseHead}
    return [pscustomobject]@{Mode='SIMULATION';Root=$root;RuntimeRoot=(Join-Path $root 'runtime');AppPath=$app;Port=([int]$Arguments.SimulationPort);EnvPath=(Join-Path $root 'production\.env');DataRoot=(Join-Path $root 'production\streamlit_opensea_sales\data_opensea_sales');RepoRoot=(Join-Path $root 'production');ReleaseRoot=(Join-Path $root 'release');ReleasePython=$Arguments.ReleasePython;BackupRoot=(Join-Path $root 'backups');PreparedReleaseManifest=$Arguments.PreparedReleaseManifest;ExpectedOldHead=$old;ExpectedReleaseHead=$release}
}
function Get-DynamicArtifactDefinitions([object]$Context) {
    $b=$Context.DataRoot
    return @(
        [pscustomobject]@{RelativePath='streamlit_opensea_sales\data_opensea_sales\market_overview_enriched\market_period_summaries.json';Path=(Join-Path $b 'market_overview_enriched\market_period_summaries.json')},
        [pscustomobject]@{RelativePath='streamlit_opensea_sales\data_opensea_sales\market_overview_enriched\market_expansion_metrics.json';Path=(Join-Path $b 'market_overview_enriched\market_expansion_metrics.json')},
        [pscustomobject]@{RelativePath='streamlit_opensea_sales\data_opensea_sales\trader_analytics_snapshot.json';Path=(Join-Path $b 'trader_analytics_snapshot.json')},
        [pscustomobject]@{RelativePath='streamlit_opensea_sales\data_opensea_sales\item_class_snapshot.json';Path=(Join-Path $b 'item_class_snapshot.json')},
        [pscustomobject]@{RelativePath='streamlit_opensea_sales\data_opensea_sales\gunzscope_supply_snapshot_v3_provider.json';Path=(Join-Path $b 'gunzscope_supply_snapshot_v3_provider.json')},
        [pscustomobject]@{RelativePath='streamlit_opensea_sales\data_opensea_sales\opensea_account_profiles_snapshot.json';Path=(Join-Path $b 'opensea_account_profiles_snapshot.json')}
    )
}
function Get-8502Process {
    $c=Get-NetTCPConnection -LocalAddress 127.0.0.1 -LocalPort 8502 -State Listen -ErrorAction SilentlyContinue|Select-Object -First 1
    if(-not $c){return $null};$p=Get-CimInstance Win32_Process -Filter ('ProcessId='+$c.OwningProcess);if(-not$p -or $p.CommandLine -notmatch '(?i)app_opensea_sales\.py' -or $p.CommandLine -match '(?i)app_gaming_marketplace\.py' -or $p.CommandLine -notmatch [regex]::Escape($script:ExpectedRoot)){throw '8502_PROCESS_IDENTITY_FAILED'};return $p
}
function Assert-ProcessIdentity([object]$Process,[object]$Context){if(-not $Process){throw 'TARGET_PROCESS_NOT_FOUND'};$cmd=[string]$Process.CommandLine;if($cmd -notmatch '(?i)app_opensea_sales\.py' -or $cmd -match '(?i)app_gaming_marketplace\.py'){throw 'TARGET_PROCESS_IDENTITY_FAILED'};if($Context.Mode -eq 'PRODUCTION' -and $cmd -notmatch [regex]::Escape($script:ExpectedRoot)){throw 'TARGET_PROCESS_ROOT_FAILED'}}
function Assert-AllowedMigrationSet([string[]]$Migrations){if($Migrations.Count -ne 3){throw 'MIGRATION_ALLOWLIST_FAILED'};for($i=0;$i -lt 3;$i++){if($Migrations[$i] -ne $script:AllowedMigrations[$i]){throw 'MIGRATION_ALLOWLIST_FAILED'}};if($Migrations -contains 'sql/add_site_product_events_trader_usd_toggle.sql'){throw 'REDUNDANT_MIGRATION_FORBIDDEN'};return $true}
function Set-ContextPhase([object]$Context,[string]$Phase){if($Context.Mode -eq 'SIMULATION'){Add-Content -LiteralPath (Join-Path $Context.Root 'phase.log') -Value $Phase};Write-KV 'PHASE' $Phase}

function Invoke-ChildProcess {
    param([string]$FilePath,[string[]]$Arguments,[string]$WorkingDirectory,[int]$TimeoutSeconds=900,[hashtable]$Environment=@{},[string]$LogPath)
    $psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$FilePath;$psi.WorkingDirectory=$WorkingDirectory;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.Arguments=(($Arguments|ForEach-Object{if($_ -match '[\s"]'){'"'+($_ -replace '(\\*)\"','$1$1\"')+'"'}else{$_}})-join ' ');foreach($k in $Environment.Keys){$psi.EnvironmentVariables[$k]=[string]$Environment[$k]};$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;if(-not$p.Start()){throw ('CHILD_START_FAILED:'+ $FilePath)};$o=$p.StandardOutput.ReadToEndAsync();$e=$p.StandardError.ReadToEndAsync();if(-not$p.WaitForExit($TimeoutSeconds*1000)){try{$p.Kill()}catch{};throw ('CHILD_TIMEOUT:'+ $FilePath)};$p.WaitForExit();$stdout=$o.Result;$stderr=$e.Result;if($LogPath){Write-AtomicText $LogPath ($stdout+[Environment]::NewLine+$stderr)};if($p.ExitCode -ne 0){throw ('CHILD_COMMAND_FAILED:'+ $FilePath+':'+$p.ExitCode)};return [pscustomobject]@{Pid=$p.Id;ExitCode=$p.ExitCode;StdOut=$stdout;StdErr=$stderr}
}
function Invoke-RefreshAdapter([object]$Context,[string]$Name,[string]$Python,[string[]]$Arguments,[string]$WorkingDirectory){if($Context.Mode -eq 'SIMULATION'){Add-Content (Join-Path $Context.Root 'refresh.commands.log') $Name;return};Invoke-ChildProcess $Python $Arguments $WorkingDirectory 1800 @{}|Out-Null}

function Invoke-BackupCore {
    param([object]$Context,[switch]$Execute)
    Assert-Context $Context|Out-Null
    if(-not$Execute){Write-KV 'MODE' 'DRY_RUN';Write-KV 'TARGET_ROOT' $Context.Root;Write-KV 'TARGET_PORT' $Context.Port;Write-KV 'BACKUP_MANIFEST_SCHEMA_VERSION' 2;Write-KV 'BACKUP_SET_VALID' 'YES';Write-KV 'MUTATION_EXECUTED' 'NO';return}
    Set-ContextPhase $Context 'BACKUP_VALIDATE';$head=$Context.ExpectedOldHead;$branch='main';if($Context.Mode -eq 'PRODUCTION'){$head=(& git -c ('safe.directory='+$Context.Root) -C $Context.Root rev-parse HEAD).Trim();$branch=(& git -c ('safe.directory='+$Context.Root) -C $Context.Root branch --show-current).Trim();if(((& git -c ('safe.directory='+$Context.Root) -C $Context.Root status --porcelain)-join '') -ne ''){throw 'PRODUCTION_WORKTREE_NOT_CLEAN'};$p=Get-8502Process;if(-not$p){throw '8502_PROCESS_NOT_FOUND'};Assert-ProcessIdentity $p $Context};if(-not(Test-Path $Context.EnvPath -PathType Leaf)){throw 'PRODUCTION_ENV_MISSING'};$processPid=0;$processExe='simulation';$processCmd='simulation app_opensea_sales.py';if($Context.Mode -eq 'PRODUCTION'){$processPid=$p.ProcessId;$processExe=$p.ExecutablePath;$processCmd=$p.CommandLine;$tools=Get-PostgresTools;foreach($n in @('pg_dump','pg_restore','psql')){if(-not$tools.ContainsKey($n)){throw ('POSTGRES_TOOL_MISSING:'+ $n)}};Get-DatabaseEnvironment $Context.EnvPath -Required|Out-Null}
    $stamp=Get-Date -Format yyyyMMdd_HHmmss;$short=$head;if($head.Length -gt 8){$short=$head.Substring(0,8)};$out=Join-Path $Context.BackupRoot ($stamp+'_'+$short);New-Item -ItemType Directory -Path $out -Force|Out-Null;$m=[ordered]@{manifest_version=2;created_at=(Get-Date).ToUniversalTime().ToString('o');target_root=$Context.Root;target_port=$Context.Port;target_app=$Context.AppPath;old_git_head=$head;old_git_branch=$branch;old_git_clean=$true;old_process_pid=$processPid;old_process_executable=$processExe;old_process_command_line_sanitized=$processCmd;old_app_path=$Context.AppPath;old_port=$Context.Port;old_runtime_root=$Context.RuntimeRoot;env_backup_relative_path='.env';git_bundle_relative_path='production.bundle';db_dump_relative_path='production.dump';db_dump_format='custom';db_dump_validation='PENDING';dynamic_artifacts=@();active_runtime_existed=$false;production_refresh_tasks=@();backup_complete=$false}
    if($Context.Mode -eq 'SIMULATION'){Set-Content (Join-Path $out 'production.bundle') 'sandbox bundle';Copy-Item $Context.EnvPath (Join-Path $out '.env');Set-Content (Join-Path $out 'production.dump') 'sandbox custom dump';$m.db_dump_validation='PASS'}else{$null=& git -c ('safe.directory='+$Context.Root) -C $Context.Root bundle create (Join-Path $out 'production.bundle') HEAD 2>&1;if($LASTEXITCODE -ne 0){throw 'GIT_BUNDLE_CREATE_FAILED'};Copy-Item $Context.EnvPath (Join-Path $out '.env');$env=Get-DatabaseEnvironment $Context.EnvPath -Required;Invoke-ChildProcess $tools.pg_dump @('--format=custom','--file',(Join-Path $out 'production.dump')) $Context.Root 1800 $env|Out-Null;Invoke-ChildProcess $tools.pg_restore @('--list',(Join-Path $out 'production.dump')) $Context.Root 300 $env|Out-Null;$m.db_dump_validation='PASS'}
    $m.env_sha256=Get-Sha256 (Join-Path $out '.env');$m.git_bundle_sha256=Get-Sha256 (Join-Path $out 'production.bundle');$m.db_dump_sha256=Get-Sha256 (Join-Path $out 'production.dump')
    foreach($d in Get-DynamicArtifactDefinitions $Context){$a=[ordered]@{relative_path=$d.RelativePath;existed_before=(Test-Path $d.Path -PathType Leaf)};if($a.existed_before){$rel='artifacts\'+[IO.Path]::GetFileName($d.Path);New-Item (Join-Path $out 'artifacts') -ItemType Directory -Force|Out-Null;Copy-Item $d.Path (Join-Path $out $rel);$a.backup_relative_path=$rel;$a.sha256_before=Get-Sha256 $d.Path;$a.size_bytes=(Get-Item $d.Path).Length};$m.dynamic_artifacts+=,$a}
    $active=Join-Path $Context.RuntimeRoot 'ACTIVE_RUNTIME.json';if(Test-Path $active -PathType Leaf){New-Item (Join-Path $out 'runtime') -ItemType Directory -Force|Out-Null;Copy-Item $active (Join-Path $out 'runtime\ACTIVE_RUNTIME.json');$m.active_runtime_existed=$true;$m.active_runtime_backup_relative_path='runtime\ACTIVE_RUNTIME.json';$m.active_runtime_sha256=Get-Sha256 $active}
    foreach($name in $script:ManagedTasks){$a=[ordered]@{task_name=$name;existed_before=$false};if($Context.Mode -eq 'SIMULATION'){$tp=Join-Path $Context.Root 'tasks.json';if(Test-Path $tp){$tasks=Get-Content $tp -Raw|ConvertFrom-Json;if($tasks.PSObject.Properties.Name -contains $name){$a.existed_before=$true;$a.state=$tasks.$name}}}else{$t=Get-ScheduledTask -TaskName $name -ErrorAction SilentlyContinue;if($t){$rel='tasks\'+$name+'.xml';New-Item (Join-Path $out 'tasks') -ItemType Directory -Force|Out-Null;Write-AtomicText (Join-Path $out $rel) (Export-ScheduledTask -TaskName $name -ErrorAction Stop);$a.existed_before=$true;$a.exported_xml_relative_path=$rel;$a.xml_sha256=Get-Sha256 (Join-Path $out $rel);$a.enabled=($t.State -ne 'Disabled')}};$m.production_refresh_tasks+=,$a}
    $m.backup_complete=$true;$manifestPath=Join-Path $out 'BACKUP_MANIFEST.json';Write-AtomicJson $manifestPath $m;Write-KV 'BACKUP_MANIFEST_SCHEMA_VERSION' 2;Write-KV 'BACKUP_MANIFEST_PATH' $manifestPath;Write-KV 'BACKUP_RESULT' 'PASS';return [pscustomobject]@{Pass=$true;ManifestPath=$manifestPath}
}

function Invoke-DerivedRefreshCore {
    param([object]$Context,[switch]$Execute)
    Assert-Context $Context|Out-Null;if(-not$Execute){Write-KV 'MODE' 'DRY_RUN';Write-KV 'DERIVED_REFRESH_PLAN' 'PASS';Write-KV 'MUTATION_EXECUTED' 'NO';return};Set-ContextPhase $Context 'DERIVED_REFRESH';$d=Get-DynamicArtifactDefinitions $Context
    if($Context.Mode -eq 'SIMULATION'){New-Item (Split-Path $d[0].Path) -ItemType Directory -Force|Out-Null;foreach($i in 0..2){Set-Content $d[$i].Path ('fresh-'+$i)}}else{if(-not(Test-Path $Context.ReleasePython -PathType Leaf)){throw 'RELEASE_PYTHON_MISSING'};$s=Join-Path $Context.RepoRoot 'scripts';Invoke-RefreshAdapter $Context 'market_period' $Context.ReleasePython @((Join-Path $s 'build_market_period_summaries.py'),'--data-dir',$Context.DataRoot) $Context.RepoRoot;Invoke-RefreshAdapter $Context 'market_expansion' $Context.ReleasePython @((Join-Path $s 'build_market_expansion_metrics.py')) $Context.RepoRoot;Invoke-RefreshAdapter $Context 'trader_analytics' $Context.ReleasePython @((Join-Path $s 'build_trader_analytics.py'),'--data-dir',$Context.DataRoot,'--output',$d[2].Path) $Context.RepoRoot}
    foreach($i in 0..2){if(-not(Test-Path $d[$i].Path -PathType Leaf) -or (Get-Item $d[$i].Path).Length -le 0){throw 'DERIVED_OUTPUT_MISSING'}};Write-KV 'DERIVED_MARKET_PERIOD' 'PASS';Write-KV 'DERIVED_MARKET_EXPANSION' 'PASS';Write-KV 'DERIVED_TRADER_ANALYTICS' 'PASS';Write-KV 'DERIVED_REFRESH' 'PASS';return [pscustomobject]@{Pass=$true}
}
function Invoke-MetadataRefreshCore {
    param([object]$Context,[switch]$Execute)
    Assert-Context $Context|Out-Null;if(-not$Execute){Write-KV 'MODE' 'DRY_RUN';Write-KV 'METADATA_REFRESH_PLAN' 'PASS';Write-KV 'MUTATION_EXECUTED' 'NO';return};Set-ContextPhase $Context 'METADATA_REFRESH';$d=Get-DynamicArtifactDefinitions $Context
    if($Context.Mode -eq 'SIMULATION'){foreach($i in 3..5){New-Item (Split-Path $d[$i].Path) -ItemType Directory -Force|Out-Null;Set-Content $d[$i].Path ('fresh-'+$i)};Add-Content (Join-Path $Context.Root 'refresh.commands.log') 'item_class';Add-Content (Join-Path $Context.Root 'refresh.commands.log') 'gunzscope_v3';Add-Content (Join-Path $Context.Root 'refresh.commands.log') 'profile_sync'}else{if(-not(Test-Path $Context.ReleasePython -PathType Leaf)){throw 'RELEASE_PYTHON_MISSING'};$s=Join-Path $Context.RepoRoot 'scripts';Invoke-RefreshAdapter $Context 'item_class' $Context.ReleasePython @((Join-Path $s 'refresh_item_class_snapshot.py')) $Context.RepoRoot;Invoke-RefreshAdapter $Context 'gunzscope_v3' $Context.ReleasePython @((Join-Path $s 'refresh_gunzscope_supply_v3_provider.py')) $Context.RepoRoot;Invoke-RefreshAdapter $Context 'profile_sync' $Context.ReleasePython @((Join-Path $s 'run_trader_profile_sync.py')) $Context.RepoRoot}
    foreach($i in 3..5){if(-not(Test-Path $d[$i].Path -PathType Leaf) -or (Get-Item $d[$i].Path).Length -le 0){throw 'METADATA_OUTPUT_MISSING'}};Write-KV 'METADATA_ITEM_CLASS' 'PASS';Write-KV 'METADATA_GUNZSCOPE_V3' 'PASS';Write-KV 'METADATA_PROFILE_SYNC' 'PASS';Write-KV 'METADATA_REFRESH' 'PASS';return [pscustomobject]@{Pass=$true}
}

function Get-DesiredTaskDefinition([object]$Context,[string]$Name){$derived=$Name -eq $script:ManagedTasks[0];$minutes=60;$sn='refresh_production_metadata.ps1';$approval='REFRESH_OTG_METADATA_8502';if($derived){$minutes=15;$sn='refresh_production_derived.ps1';$approval='REFRESH_OTG_DERIVED_8502'};$q=[char]34;$path=Join-Path $Context.Root ('ops\production\'+$sn);return [ordered]@{task_name=$Name;executable='PowerShell.exe';arguments=('-NoProfile -ExecutionPolicy Bypass -File '+$q+$path+$q+' -Execute -ApprovalPhrase '+$approval+' -ReleasePython '+$q+$Context.ReleasePython+$q);working_directory=$Context.Root;interval_minutes=$minutes;multiple_instances='IgnoreNew';start_when_available=$true;principal='SYSTEM';run_level='Highest';enabled=$true}}
function Test-TaskDefinitionMatch([object]$Existing,[object]$Desired){if(-not$Existing){return $false};foreach($k in @('executable','arguments','working_directory','interval_minutes','multiple_instances','start_when_available','principal','run_level','enabled')){if([string]$Existing.$k -ne [string]$Desired[$k]){return $false}};return $true}
function Invoke-TaskConfigurationCore {
    param([object]$Context,[switch]$Execute)
    Assert-Context $Context|Out-Null;if(-not$Execute){Write-KV 'MODE' 'DRY_RUN';Write-KV 'TASK_CONFIGURATION_PLAN' 'PASS';Write-KV 'PRODUCTION_REFRESH_TASK_COLLISION_POLICY' 'FAIL_CLOSED';foreach($n in $script:ManagedTasks){Write-KV ('TASK_'+$n) ((Get-DesiredTaskDefinition $Context $n)|ConvertTo-Json -Compress)};Write-KV 'MUTATION_EXECUTED' 'NO';return};Set-ContextPhase $Context 'TASK_CONFIGURATION'
    if($Context.Mode -eq 'SIMULATION'){$old=$null;$tp=Join-Path $Context.Root 'tasks.json';if(Test-Path $tp){$old=Get-Content $tp -Raw|ConvertFrom-Json};$new=@{};foreach($n in $script:ManagedTasks){$d=Get-DesiredTaskDefinition $Context $n;if($old -and $old.PSObject.Properties.Name -contains $n -and -not(Test-TaskDefinitionMatch $old.$n $d)){throw ('TASK_COLLISION:'+ $n)};$new[$n]=[pscustomobject]$d};Write-AtomicJson (Join-Path $Context.Root 'tasks.json') $new}else{foreach($n in $script:ManagedTasks){$d=Get-DesiredTaskDefinition $Context $n;$existing=Get-ScheduledTask -TaskName $n -ErrorAction SilentlyContinue;if($existing){$a=$existing.Actions|Select-Object -First 1;$set=$existing.Settings;if(\"$($a.Execute)\" -notmatch '(?i)power' -or \"$($a.Arguments)\" -ne $d.arguments -or \"$($a.WorkingDirectory)\" -ne $d.working_directory -or \"$($set.MultipleInstances)\" -ne 'IgnoreNew' -or -not $set.StartWhenAvailable){throw ('TASK_COLLISION:'+ $n)};continue};$act=New-ScheduledTaskAction -Execute $d.executable -Argument $d.arguments -WorkingDirectory $d.working_directory;$tr=New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) -RepetitionInterval (New-TimeSpan -Minutes $d.interval_minutes) -RepetitionDuration (New-TimeSpan -Days 3650);$set=New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew -StartWhenAvailable;Register-ScheduledTask -TaskName $n -Action $act -Trigger $tr -Settings $set -RunLevel Highest -User SYSTEM -ErrorAction Stop|Out-Null}}
    Write-KV 'TASK_CONFIGURATION' 'PASS';Write-KV 'PRODUCTION_REFRESH_TASKS' 'PASS';return [pscustomobject]@{Pass=$true}
}

function Read-BackupManifest([string]$Path,[object]$Context){if(-not(Test-Path $Path -PathType Leaf)){throw 'BACKUP_MANIFEST_MISSING'};$m=Get-Content $Path -Raw|ConvertFrom-Json;if($m.manifest_version -ne 2 -or -not$m.backup_complete -or $m.target_root -ne $Context.Root -or [int]$m.target_port -ne $Context.Port -or $m.target_app -ne $Context.AppPath){throw 'BACKUP_MANIFEST_INVALID'};$base=Split-Path $Path -Parent;foreach($pair in @(@('env_backup_relative_path','env_sha256'),@('git_bundle_relative_path','git_bundle_sha256'),@('db_dump_relative_path','db_dump_sha256'))){$p=Join-Path $base $m.($pair[0]);if(-not(Test-Path $p -PathType Leaf) -or (Get-Sha256 $p) -ne [string]$m.($pair[1])){throw 'BACKUP_MANIFEST_HASH_MISMATCH'}};if($m.db_dump_format -ne 'custom' -or $m.db_dump_validation -ne 'PASS'){throw 'BACKUP_DB_VALIDATION_MISSING'};if(@($m.dynamic_artifacts).Count -ne 6 -or @($m.production_refresh_tasks).Count -ne 2){throw 'BACKUP_MANIFEST_STATE_INCOMPLETE'};foreach($a in @($m.dynamic_artifacts)){if($a.existed_before){$p=Join-Path $base $a.backup_relative_path;if(-not(Test-Path $p -PathType Leaf) -or (Get-Sha256 $p) -ne [string]$a.sha256_before){throw 'BACKUP_ARTIFACT_HASH_MISMATCH'}}};return [pscustomobject]@{Manifest=$m;Base=$base}}
function Set-FailClosedEnv([object]$Context){$lines=@();if(Test-Path $Context.EnvPath){$lines=Get-Content $Context.EnvPath};$updates=@{GUNZSCOPE_SUPPLY_SOURCE='v3';OTG_ANALYTICS_WRITES_ENABLED='false';OTG_SITE_ANALYTICS_ENABLED='false';OTG_PRODUCT_EVENTS_ENABLED='false';OTG_FEEDBACK_WRITES_ENABLED='false';OTG_FEEDBACK_TELEGRAM_ENABLED='false'};$seen=@{};$new=@();foreach($l in $lines){if($l -match '^\s*([^#=][^=]*)='){$k=$Matches[1].Trim();if($updates.ContainsKey($k)){$new+=($k+'='+$updates[$k]);$seen[$k]=$true}else{$new+=$l}}else{$new+=$l}};foreach($k in $updates.Keys){if(-not$seen.ContainsKey($k)){$new+=($k+'='+$updates[$k])}};Write-AtomicText $Context.EnvPath (($new -join [Environment]::NewLine)+[Environment]::NewLine)}
function Invoke-ContextMigrations([object]$Context){Assert-AllowedMigrationSet $script:AllowedMigrations|Out-Null;if($Context.Mode -eq 'SIMULATION'){Set-Content (Join-Path $Context.Root 'migrations.log') ($script:AllowedMigrations -join [Environment]::NewLine);return};$tools=Get-PostgresTools;if(-not$tools.ContainsKey('psql')){throw 'PSQL_MISSING'};$env=Get-DatabaseEnvironment $Context.EnvPath -Required;foreach($m in $script:AllowedMigrations){$p=Join-Path $Context.RepoRoot $m;if(-not(Test-Path $p)){throw ('MIGRATION_MISSING:'+ $m)};Invoke-ChildProcess $tools.psql @('-X','-v','ON_ERROR_STOP=1','-f',$p) $Context.Root 300 $env|Out-Null}}
function Invoke-ContextGitFastForward([object]$Context,[string]$ReleaseHead){if($Context.Mode -eq 'SIMULATION'){$s=Get-Content (Join-Path $Context.Root 'simulation_state.json') -Raw|ConvertFrom-Json;$s.current_head=$ReleaseHead;Write-AtomicJson (Join-Path $Context.Root 'simulation_state.json') $s;return};& git -c ('safe.directory='+$Context.Root) -C $Context.Root fetch origin main;if($LASTEXITCODE -ne 0){throw 'GIT_FETCH_FAILED'};& git -c ('safe.directory='+$Context.Root) -C $Context.Root merge --ff-only origin/main;if($LASTEXITCODE -ne 0){throw 'GIT_FAST_FORWARD_FAILED'}}
function Invoke-ContextGitReset([object]$Context,[string]$OldHead){if($Context.Mode -eq 'SIMULATION'){$s=Get-Content (Join-Path $Context.Root 'simulation_state.json') -Raw|ConvertFrom-Json;$s.current_head=$OldHead;Write-AtomicJson (Join-Path $Context.Root 'simulation_state.json') $s;return};& git -c ('safe.directory='+$Context.Root) -C $Context.Root reset --hard $OldHead;if($LASTEXITCODE -ne 0){throw 'GIT_ROLLBACK_FAILED'}}
function Invoke-ContextStopProcess([object]$Context){if($Context.Mode -eq 'SIMULATION'){$s=Get-Content (Join-Path $Context.Root 'simulation_state.json') -Raw|ConvertFrom-Json;$s.process='stopped';Write-AtomicJson (Join-Path $Context.Root 'simulation_state.json') $s;return};$p=Get-8502Process;if(-not$p){throw '8502_PROCESS_NOT_FOUND'};Assert-ProcessIdentity $p $Context;Stop-Process -Id $p.ProcessId -Force;for($i=0;$i-lt 60;$i++){if(-not(Get-8502Process)){return};Start-Sleep -Milliseconds 500};throw '8502_DID_NOT_STOP'}
function Invoke-ContextStartProcess([object]$Context,[string]$Python,[string]$LogPath,[switch]$Old){if($Context.Mode -eq 'SIMULATION'){$s=Get-Content (Join-Path $Context.Root 'simulation_state.json') -Raw|ConvertFrom-Json;$state='new-healthy';if($Old){$state='old-healthy'}elseif($s.fail_new_health){$state='new-failed'};$s.process=$state;Write-AtomicJson (Join-Path $Context.Root 'simulation_state.json') $s;return [pscustomobject]@{Pid=18502}};if(-not(Test-Path $Python -PathType Leaf)){throw 'RUNTIME_PYTHON_MISSING'};$args=@('-m','streamlit','run',$Context.AppPath,'--server.address','127.0.0.1','--server.port','8502','--server.fileWatcherType','none','--browser.gatherUsageStats','false');$safe=Get-SafeEnv $Context.EnvPath;$oldEnv=@{};foreach($k in $safe.Keys){$oldEnv[$k]=[Environment]::GetEnvironmentVariable($k,'Process');[Environment]::SetEnvironmentVariable($k,[string]$safe[$k],'Process')};try{$p=Start-Process -FilePath $Python -ArgumentList $args -WorkingDirectory (Split-Path $Context.AppPath) -RedirectStandardOutput $LogPath -RedirectStandardError ($LogPath+'.err') -PassThru -WindowStyle Hidden}finally{foreach($k in $safe.Keys){[Environment]::SetEnvironmentVariable($k,$oldEnv[$k],'Process')}};return $p}

function Invoke-DeployCore {
    param([object]$Context,[switch]$Execute)
    Assert-Context $Context|Out-Null;if(-not$Execute){Write-KV 'MODE' 'DRY_RUN';Write-KV 'DEPLOY_PLAN' 'PASS';Write-KV 'MAIN_PROMOTION_REQUIRED' 'YES';Write-KV 'MUTATION_EXECUTED' 'NO';return};Set-ContextPhase $Context 'DEPLOY_VALIDATE'
    if($Context.Mode -eq 'PRODUCTION'){if(-not$Context.ExpectedOldHead -or -not$Context.ExpectedReleaseHead -or -not$Context.ReleasePython -or -not$Context.PreparedReleaseManifest){throw 'DEPLOY_INPUTS_MISSING'};$actual=(& git -c ('safe.directory='+$Context.Root) -C $Context.Root rev-parse HEAD).Trim();if($actual -ne $Context.ExpectedOldHead){throw 'EXPECTED_OLD_HEAD_MISMATCH'};if(((& git -c ('safe.directory='+$Context.Root) -C $Context.Root status --porcelain)-join '') -ne ''){throw 'PRODUCTION_WORKTREE_NOT_CLEAN'};$main=(& git -c ('safe.directory='+$Context.Root) -C $Context.Root rev-parse origin/main).Trim();if($main -ne $Context.ExpectedReleaseHead){throw 'MAIN_PROMOTION_REQUIRED'};if(-not(Test-Path $Context.ReleaseRoot -PathType Container)){throw 'RELEASE_ROOT_MISSING'}}else{$s=Get-Content (Join-Path $Context.Root 'simulation_state.json') -Raw|ConvertFrom-Json;if($s.main_head -ne $Context.ExpectedReleaseHead){throw 'MAIN_PROMOTION_REQUIRED'}};$null=Read-BackupManifest $Context.PreparedReleaseManifest $Context;Assert-AllowedMigrationSet $script:AllowedMigrations|Out-Null;$stopped=$false
    try{Set-ContextPhase $Context 'DEPLOY_STOP';Invoke-ContextStopProcess $Context;$stopped=$true;Set-ContextPhase $Context 'DEPLOY_FAST_FORWARD';Invoke-ContextGitFastForward $Context $Context.ExpectedReleaseHead;Set-ContextPhase $Context 'DEPLOY_ENV';Set-FailClosedEnv $Context;Set-ContextPhase $Context 'DEPLOY_MIGRATIONS';Invoke-ContextMigrations $Context;Set-ContextPhase $Context 'DEPLOY_DERIVED';Invoke-DerivedRefreshCore $Context -Execute|Out-Null;Set-ContextPhase $Context 'DEPLOY_METADATA';Invoke-MetadataRefreshCore $Context -Execute|Out-Null;Set-ContextPhase $Context 'DEPLOY_READERS';foreach($d in Get-DynamicArtifactDefinitions $Context){if(-not(Test-Path $d.Path -PathType Leaf)){throw 'DEPLOY_ARTIFACT_VALIDATION_FAILED'}};Set-ContextPhase $Context 'DEPLOY_START';$new=Invoke-ContextStartProcess $Context $Context.ReleasePython (Join-Path $Context.Root 'deployment.log');Set-ContextPhase $Context 'DEPLOY_HEALTH';$healthy=$false;if($Context.Mode -eq 'SIMULATION'){$healthy=(Get-Content (Join-Path $Context.Root 'simulation_state.json') -Raw|ConvertFrom-Json).process -eq 'new-healthy'}else{$healthy=Invoke-HealthCheck 8502 60};if(-not$healthy){throw 'NEW_PRODUCTION_HEALTH_FAILED'};Set-ContextPhase $Context 'DEPLOY_TASKS';Invoke-TaskConfigurationCore $Context -Execute|Out-Null;Write-AtomicJson (Join-Path $Context.Root 'DEPLOYMENT_RECEIPT.json') ([ordered]@{old_head=$Context.ExpectedOldHead;new_head=$Context.ExpectedReleaseHead;new_pid=$new.Pid;sql_migration_count=3;dynamic_artifact_count=6;health='PASS'});Write-KV 'DEPLOY_RESULT' 'PASS';return [pscustomobject]@{Pass=$true}}catch{if($stopped){Write-KV 'DEPLOY_FAILURE_AFTER_DOWNTIME_STARTED' 'YES';try{Invoke-RollbackCore $Context -Execute -Automatic|Out-Null}catch{Write-KV 'ROLLBACK_FAILURE' $_.Exception.Message}};throw}
}
function Invoke-HealthCheck([int]$Port,[int]$TimeoutSeconds=60){$until=(Get-Date).AddSeconds($TimeoutSeconds);do{try{$r=Invoke-WebRequest ('http://127.0.0.1:'+ $Port) -UseBasicParsing -TimeoutSec 5;if($r.StatusCode -ge 200 -and $r.StatusCode -lt 500){return $true}}catch{};Start-Sleep -Milliseconds 500}while((Get-Date)-lt $until);return $false}
function Invoke-RollbackCore {
    param([object]$Context,[switch]$Execute,[switch]$Automatic)
    Assert-Context $Context|Out-Null;if(-not$Execute){Write-KV 'MODE' 'DRY_RUN';Write-KV 'ROLLBACK_PLAN' 'PASS';Write-KV 'DB_SCHEMA_ROLLBACK' 'NOT_AUTOMATIC';Write-KV 'REMOTE_MAIN_ROLLBACK' 'NOT_AUTOMATIC';Write-KV 'MUTATION_EXECUTED' 'NO';return};Set-ContextPhase $Context 'ROLLBACK_VALIDATE';$b=Read-BackupManifest $Context.PreparedReleaseManifest $Context;$m=$b.Manifest;Set-ContextPhase $Context 'ROLLBACK_STOP';if($Context.Mode -eq 'SIMULATION'){Invoke-ContextStopProcess $Context}else{$p=Get-8502Process;if($p){Assert-ProcessIdentity $p $Context;Invoke-ContextStopProcess $Context}};Set-ContextPhase $Context 'ROLLBACK_GIT';Invoke-ContextGitReset $Context ([string]$m.old_git_head);Set-ContextPhase $Context 'ROLLBACK_ENV';Copy-Item (Join-Path $b.Base $m.env_backup_relative_path) $Context.EnvPath -Force;if((Get-Sha256 $Context.EnvPath) -ne [string]$m.env_sha256){throw 'ROLLBACK_ENV_HASH_MISMATCH'};Set-ContextPhase $Context 'ROLLBACK_ARTIFACTS';foreach($a in @($m.dynamic_artifacts)){$target=(Get-DynamicArtifactDefinitions $Context|Where-Object RelativePath -eq $a.relative_path).Path;if($a.existed_before){Copy-Item (Join-Path $b.Base $a.backup_relative_path) $target -Force;if((Get-Sha256 $target) -ne [string]$a.sha256_before){throw 'ROLLBACK_ARTIFACT_STATE_MISMATCH'}}elseif(Test-Path $target -PathType Leaf){Remove-Item -LiteralPath $target -Force}};Set-ContextPhase $Context 'ROLLBACK_TASKS';if($Context.Mode -eq 'SIMULATION'){$old=@{};foreach($t in @($m.production_refresh_tasks)){if($t.existed_before){$old[$t.task_name]=$t.state}};Write-AtomicJson (Join-Path $Context.Root 'tasks.json') $old}else{foreach($n in $script:ManagedTasks){$e=@($m.production_refresh_tasks|Where-Object task_name -eq $n)[0];$existing=Get-ScheduledTask -TaskName $n -ErrorAction SilentlyContinue;if($e.existed_before){Register-ScheduledTask -TaskName $n -Xml (Get-Content (Join-Path $b.Base $e.exported_xml_relative_path) -Raw) -Force|Out-Null}elseif($existing){Unregister-ScheduledTask -TaskName $n -Confirm:$false}}};Set-ContextPhase $Context 'ROLLBACK_RUNTIME';$active=Join-Path $Context.RuntimeRoot 'ACTIVE_RUNTIME.json';if($m.active_runtime_existed){Copy-Item (Join-Path $b.Base $m.active_runtime_backup_relative_path) $active -Force}elseif(Test-Path $active -PathType Leaf){Remove-Item -LiteralPath $active -Force};Set-ContextPhase $Context 'ROLLBACK_START';$py=$Context.ReleasePython;if($m.old_process_executable -and $m.old_process_executable -ne 'simulation'){$py=$m.old_process_executable};$old=Invoke-ContextStartProcess $Context $py (Join-Path $Context.Root 'rollback.log') -Old;Set-ContextPhase $Context 'ROLLBACK_HEALTH';$healthy=$true;if($Context.Mode -eq 'PRODUCTION'){$healthy=Invoke-HealthCheck 8502 60};if(-not$healthy){throw 'ROLLBACK_OLD_APP_HEALTH_FAILED'};Write-KV 'DB_SCHEMA_ROLLBACK' 'NOT_AUTOMATIC';Write-KV 'REMOTE_MAIN_ROLLBACK' 'NOT_AUTOMATIC';Write-KV 'ROLLBACK_RESULT' 'PASS';return [pscustomobject]@{Pass=$true}
}
