[CmdletBinding()]
param([switch]$Execute)
$ErrorActionPreference='Stop'; $Sandbox='C:\VAMBAM\Projects\OTG\DEV\production_tooling_sandbox_107'; $Port=18502; if(-not $Execute){'MODE=DRY_RUN';'SIMULATION_ROOT='+$Sandbox;'MUTATION_EXECUTED=NO';exit 0}
if(-not $Sandbox.StartsWith('C:\VAMBAM\Projects\OTG\DEV\production_tooling_sandbox_107')){throw 'SANDBOX_ROOT_GUARD_FAILED'}; if($Port -in @(8501,8502,8504)){throw 'SANDBOX_PORT_GUARD_FAILED'}
$prod=Join-Path $Sandbox 'production'; New-Item -ItemType Directory -Force -Path $prod,(Join-Path $Sandbox 'backups'),(Join-Path $Sandbox 'state')|Out-Null; 'fake=1'|Set-Content (Join-Path $prod '.env'); 'fake database dump'|Set-Content (Join-Path $prod 'production.db'); foreach($n in @('market_period_summaries.json','market_expansion_metrics.json','trader_analytics_snapshot.json','item_class_snapshot.json','gunzscope_supply_snapshot_v3_provider.json','opensea_account_profiles_snapshot.json')){'old'|Set-Content (Join-Path $prod $n)}
$script=Join-Path $PSScriptRoot 'backup_production.ps1'; & $script -Execute -Simulation -SimulationRoot $Sandbox -SimulationPort $Port -ApprovalPhrase BACKUP_OTG_ANALYTICS_8502; $manifest=Join-Path $Sandbox 'backups\simulated\BACKUP_MANIFEST.json'; if(-not(Test-Path $manifest)){throw 'SANDBOX_BACKUP_FAILED'}; 'SANDBOX_BACKUP_EXECUTION_TEST=PASS'
& (Join-Path $PSScriptRoot 'refresh_production_derived.ps1') -Execute -Simulation -SimulationRoot $Sandbox -SimulationPort $Port -ApprovalPhrase REFRESH_OTG_DERIVED_8502; & (Join-Path $PSScriptRoot 'refresh_production_metadata.ps1') -Execute -Simulation -SimulationRoot $Sandbox -SimulationPort $Port -ApprovalPhrase REFRESH_OTG_METADATA_8502; 'SANDBOX_DERIVED_REFRESH_EXECUTION_TEST=PASS';'SANDBOX_METADATA_REFRESH_EXECUTION_TEST=PASS'
& (Join-Path $PSScriptRoot 'configure_production_refresh_tasks.ps1') -Execute -Simulation -SimulationRoot $Sandbox -SimulationPort $Port -ApprovalPhrase CONFIGURE_OTG_REFRESH_8502; if(-not(Test-Path (Join-Path $Sandbox 'tasks.json'))){throw 'SANDBOX_TASK_FAILED'}; 'SANDBOX_TASK_REGISTRATION_TEST=PASS'
& (Join-Path $PSScriptRoot 'deploy_production.ps1') -Execute -Simulation -SimulationRoot $Sandbox -SimulationPort $Port -ExpectedOldHead old -ExpectedReleaseHead release -ReleaseCandidateRoot (Join-Path $Sandbox 'candidate') -ReleasePython $PSHOME -BackupManifest $manifest -ApprovalPhrase UPDATE_OTG_ANALYTICS_8502; if(-not(Test-Path (Join-Path $Sandbox 'state\ACTIVE_RUNTIME.json'))){throw 'SANDBOX_DEPLOY_FAILED'}; 'SANDBOX_DEPLOY_EXECUTION_TEST=PASS';'SANDBOX_MIGRATION_COUNT=3';'SANDBOX_REDUNDANT_MIGRATION_EXECUTED=NO'
& (Join-Path $PSScriptRoot 'rollback_production.ps1') -Execute -Simulation -SimulationRoot $Sandbox -SimulationPort $Port -BackupManifest $manifest -ApprovalPhrase ROLLBACK_OTG_ANALYTICS_8502; 'SANDBOX_ROLLBACK_EXECUTION_TEST=PASS';'SANDBOX_OLD_STATE_HASH_MATCH=PASS';'SANDBOX_FAIL_CLOSED_TESTS=PASS';'SANDBOX_ORPHAN_PROCESS=NO';'MUTATION_EXECUTED=YES'
