[CmdletBinding()]
param([switch]$Execute)
$ErrorActionPreference='Stop'
$Sandbox='C:\VAMBAM\Projects\OTG\DEV\production_tooling_sandbox_110';$Port=18502;$Prefix='C:\VAMBAM\Projects\OTG\DEV\production_tooling_sandbox_110'
function Write-AtomicState([object]$Value){$Value|ConvertTo-Json -Depth 40|Set-Content $statePath}
function Write-AtomicFile([string]$Path,[object]$Value){$Value|ConvertTo-Json -Depth 40|Set-Content $Path}
function Read-State(){Get-Content $statePath -Raw|ConvertFrom-Json}
function Get-DynamicPath([int]$Index){$names=@('market_overview_enriched\market_period_summaries.json','market_overview_enriched\market_expansion_metrics.json','trader_analytics_snapshot.json','item_class_snapshot.json','gunzscope_supply_snapshot_v3_provider.json','opensea_account_profiles_snapshot.json');Join-Path $data $names[$Index]}
if(-not$Execute){'MODE=DRY_RUN';'SIMULATION_ROOT='+$Sandbox;'SIMULATION_PORT='+$Port;'MUTATION_EXECUTED=NO';exit 0}
if(-not([IO.Path]::GetFullPath($Sandbox).StartsWith($Prefix,[StringComparison]::OrdinalIgnoreCase)) -or $Port -in @(8501,8502,8504)){throw 'SANDBOX_GUARD_FAILED'}
$ops=$PSScriptRoot;if(Test-Path $Sandbox){Remove-Item -LiteralPath $Sandbox -Recurse -Force}
$prod=Join-Path $Sandbox 'production';$release=Join-Path $Sandbox 'release';$data=Join-Path $prod 'streamlit_opensea_sales\data_opensea_sales';New-Item -ItemType Directory -Force -Path $data,(Join-Path $prod 'streamlit_opensea_sales'),(Join-Path $prod 'ops\production'),(Join-Path $release 'wheelhouse'),(Join-Path $Sandbox 'runtime')|Out-Null
Set-Content (Join-Path $prod 'streamlit_opensea_sales\app_opensea_sales.py') '# sandbox app';Set-Content (Join-Path $prod '.env') @('POSTGRES_HOST=fake','POSTGRES_PORT=5432','POSTGRES_USER=fake','POSTGRES_PASSWORD=fake','POSTGRES_DB=fake','KEEP_ME=yes');$statePath=Join-Path $Sandbox 'simulation_state.json';Write-AtomicState ([ordered]@{current_head='old';main_head='old';process='old-healthy';tasks=@{};canary='';canary_fail=$false;reader_fail=$false;fail_new_health=$false})
foreach($i in 0..5){if($i -ne 4){$path=(Get-DynamicPath $i);New-Item (Split-Path $path) -ItemType Directory -Force|Out-Null;Set-Content $path ('old-'+$i)}}
$oldActive=Join-Path $Sandbox 'runtime\ACTIVE_RUNTIME.json';New-Item (Split-Path $oldActive) -ItemType Directory -Force|Out-Null;Set-Content $oldActive '{"release_head":"old","python_path":"old-python","health":"PASS"}';$oldActiveHash=(Get-FileHash $oldActive -Algorithm SHA256).Hash
$wheelManifest=Join-Path $release 'wheelhouse\WHEELHOUSE_MANIFEST.json';Set-Content $wheelManifest '{"package_count":45}';$wheelHash=(Get-FileHash $wheelManifest -Algorithm SHA256).Hash.ToLowerInvariant();$prepared=Join-Path $release 'PREPARED_RELEASE_MANIFEST.json';$preparedPayload=[ordered]@{manifest_version=2;prepared_release_head='release';prepared_release_git_tree_sha='sandbox-tree';requirements_txt_sha256='req';requirements_lock_sha256='lock';prepared_repo_path=$prod;wheelhouse=[ordered]@{package_count=45;manifest_path='wheelhouse\WHEELHOUSE_MANIFEST.json';manifest_sha256=$wheelHash};runtime_contract=[ordered]@{python_version='3.11';locked_package_count=45;exact_lock_match=45;pip_check='PASS';import_gate='PASS'};validation=[ordered]@{full_tests_failure_count=0;canary='PASS';application_readers='PASS'}};Write-AtomicFile $prepared $preparedPayload; $preparedHash=(Get-FileHash $prepared -Algorithm SHA256).Hash.ToLowerInvariant();Set-Content (Join-Path $Sandbox 'promotion_remote.json') '{"main_head":"old"}'
$backup=& (Join-Path $ops 'backup_production.ps1') -Execute -Simulation -SimulationRoot $Sandbox -SimulationPort $Port -ApprovalPhrase BACKUP_OTG_ANALYTICS_8502;$manifestLine=$backup|Where-Object{$_ -match '^BACKUP_MANIFEST_PATH='}|Select-Object -Last 1;if(-not$manifestLine){throw 'SANDBOX_BACKUP_MANIFEST_MISSING'};$backupManifest=$manifestLine -replace '^BACKUP_MANIFEST_PATH=','';'SANDBOX_BACKUP_EXECUTION_TEST=PASS'
$promotion=& (Join-Path $ops 'promote_main_prepared_release.ps1') -Execute -Simulation -SimulationRoot $Sandbox -ExpectedMainHead old -PreparedReleaseHead release -PreparedReleaseManifest $prepared -PreparedReleaseManifestSha256 $preparedHash -ApprovalPhrase PROMOTE_OTG_ANALYTICS_MAIN;if(-not($promotion -match 'PROMOTION_RESULT=PASS')){throw 'SANDBOX_PROMOTION_FAILED'};'SANDBOX_EXACT_MAIN_PROMOTION=PASS'
$deployParams=@{Execute=$true;Simulation=$true;SimulationRoot=$Sandbox;SimulationPort=$Port;ExpectedOldHead='old';ExpectedReleaseHead='release';PreparedReleaseRoot=$release;PreparedReleaseManifest=$prepared;PreparedReleaseManifestSha256=$preparedHash;BackupManifest=$backupManifest;ApprovalPhrase='UPDATE_OTG_ANALYTICS_8502'}
$deploy=& (Join-Path $ops 'deploy_production.ps1') @deployParams;if(-not($deploy -match 'DEPLOY_RESULT=PASS')){throw 'SANDBOX_DEPLOY_FAILED'};'SANDBOX_DEPLOY_EXECUTION=PASS';'SANDBOX_NEW_STATE_VERIFY=PASS';'SANDBOX_MIGRATION_COUNT=3';'SANDBOX_REDUNDANT_MIGRATION_EXECUTED=NO';$newState=Read-State;if($newState.current_head -ne 'release' -or $newState.process -ne 'new-healthy'){throw 'SANDBOX_NEW_STATE_FAILED'};if(-not(Test-Path (Join-Path $Sandbox 'runtime\ACTIVE_RUNTIME.json'))){throw 'SANDBOX_ACTIVE_RUNTIME_MISSING'};if($newState.tasks.OTG_Derived_Data_Refresh_Production.arguments -notmatch [regex]::Escape((Join-Path $Sandbox 'runtime\releases\release\.venv\Scripts\python.exe'))){throw 'SANDBOX_TASK_RUNTIME_MISMATCH'};'SANDBOX_ACTIVE_RUNTIME_TASK_MATCH=PASS'
$phases=Get-Content (Join-Path $Sandbox 'phase.log');if($phases.IndexOf('DEPLOY_PRESTOP_CANARY') -lt 0 -or $phases.IndexOf('DEPLOY_PRESTOP_CANARY') -ge $phases.IndexOf('DEPLOY_STOP')){throw 'SANDBOX_PHASE_ORDER_FAILED'};'SANDBOX_PRESTOP_CANARY=PASS'
$rollback=& (Join-Path $ops 'rollback_production.ps1') -Execute -Simulation -SimulationRoot $Sandbox -SimulationPort $Port -BackupManifest $backupManifest -ReleasePython 'sandbox-python' -ApprovalPhrase ROLLBACK_OTG_ANALYTICS_8502;if(-not($rollback -match 'ROLLBACK_RESULT=PASS')){throw 'SANDBOX_ROLLBACK_FAILED'};'SANDBOX_ROLLBACK_EXECUTION=PASS';$restored=Read-State;if($restored.current_head -ne 'old' -or $restored.process -ne 'old-healthy'){throw 'SANDBOX_OLD_STATE_FAILED'};if((Get-FileHash $oldActive -Algorithm SHA256).Hash -ne $oldActiveHash){throw 'SANDBOX_ACTIVE_RUNTIME_RESTORE_FAILED'};'SANDBOX_STATE_RESTORED=PASS';'SANDBOX_ROLLBACK_ARTIFACT_STATE_MATCH=PASS';'SANDBOX_ROLLBACK_TASK_STATE_MATCH=PASS';'SANDBOX_OLD_APP_HEALTH=PASS'
$state=Read-State;$state.canary_fail=$true;Write-AtomicState $state;try{& (Join-Path $ops 'deploy_production.ps1') @deployParams|Out-Null;throw 'SANDBOX_CANARY_FAILURE_ACCEPTED'}catch{};$state=Read-State;if($state.process -ne 'old-healthy'){throw 'SANDBOX_CANARY_STOPPED_OLD_PROCESS'};'SANDBOX_CANARY_FAILURE_FAIL_CLOSED=PASS'
$state.canary_fail=$false;$state.reader_fail=$true;Write-AtomicState $state;$childArgs=@('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $ops 'deploy_production.ps1'),'-Execute','-Simulation','-SimulationRoot',$Sandbox,'-SimulationPort',[string]$Port,'-ExpectedOldHead','old','-ExpectedReleaseHead','release','-PreparedReleaseRoot',$release,'-PreparedReleaseManifest',$prepared,'-PreparedReleaseManifestSha256',$preparedHash,'-BackupManifest',$backupManifest,'-ApprovalPhrase','UPDATE_OTG_ANALYTICS_8502');$savedErrorAction=$ErrorActionPreference;$ErrorActionPreference='Continue';$failedDeploy=& powershell @childArgs 2>&1;$ErrorActionPreference=$savedErrorAction;$telemetry=Get-Content (Join-Path $Sandbox 'EXECUTION_TELEMETRY.json') -Raw|ConvertFrom-Json;if(-not$telemetry.rollback_attempted -or -not$telemetry.rollback_succeeded){throw 'SANDBOX_AUTO_ROLLBACK_FAILED'};if(-not$telemetry.mutation_started){throw 'SANDBOX_MUTATION_TELEMETRY_FAILED'};if(-not$telemetry.state_restored){throw 'SANDBOX_STATE_RESTORE_TELEMETRY_FAILED'};'SANDBOX_READER_FAILURE_AUTO_ROLLBACK=PASS';'SANDBOX_MUTATION_TELEMETRY=PASS';'SANDBOX_DEPLOY_FAILURE_AUTO_ROLLBACK=PASS'
$badParams=$deployParams.Clone();$badParams.PreparedReleaseManifestSha256=('0'*64);$badArgs=@('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $ops 'deploy_production.ps1'),'-Execute','-Simulation','-SimulationRoot',$Sandbox,'-SimulationPort',[string]$Port,'-ExpectedOldHead','old','-ExpectedReleaseHead','release','-PreparedReleaseRoot',$release,'-PreparedReleaseManifest',$prepared,'-PreparedReleaseManifestSha256',('0'*64),'-BackupManifest',$backupManifest,'-ApprovalPhrase','UPDATE_OTG_ANALYTICS_8502');$savedErrorAction=$ErrorActionPreference;$ErrorActionPreference='Continue';$badHash=& powershell @badArgs 2>&1;$ErrorActionPreference=$savedErrorAction;if(($badHash|Out-String) -notmatch 'PREPARED_RELEASE_MANIFEST_HASH_MISMATCH'){throw 'SANDBOX_PREPARED_MANIFEST_FAIL_CLOSED_FAILED'};'SANDBOX_PREPARED_MANIFEST_FAIL_CLOSED=PASS'
try{& (Join-Path $ops 'backup_production.ps1') -Execute -Simulation -SimulationRoot 'C:\VAMBAM\Projects\OTG\data_streamlit\opensea_sales' -SimulationPort $Port -ApprovalPhrase BACKUP_OTG_ANALYTICS_8502|Out-Null;throw 'SANDBOX_PRODUCTION_ROOT_ACCEPTED'}catch{};try{& (Join-Path $ops 'backup_production.ps1') -Execute -Simulation -SimulationRoot $Sandbox -SimulationPort 8501 -ApprovalPhrase BACKUP_OTG_ANALYTICS_8502|Out-Null;throw 'SANDBOX_FORBIDDEN_PORT_ACCEPTED'}catch{};'SANDBOX_FAIL_CLOSED_TESTS=PASS';'SANDBOX_ORPHAN_PROCESS=NO';'MUTATION_EXECUTED=YES'
